### PR TITLE
SQL-997: Add support for casting datetime to int

### PR DESCRIPTION
**Pull request by nbagnard**

### CODE REVIEW

**Review by bucaojit — APPROVED** [review]
LGTM!

**Review by mattChiaravalloti — APPROVED** [review]
looks good -- could be worth adding a comment explaining the formula on this one too!

**Comment by nbagnard** [comment]
> looks good -- could be worth adding a comment explaining the formula on this one too!

Very good idea. It is explained in the JIRA, but it certainly makes total sense to add it here! Thank you for noting this :)

**Comment by nbagnard** [comment]
evergreen merge

**Pull request merged**
