### PR TITLE
SQL-1013: Convert NaN to Null in Tableau formulas using POW()

### PR DESCRIPTION
**Pull request by nbagnard**

### CODE REVIEW

**Review by bucaojit — CHANGES_REQUESTED** [review]
`POW()` is also used in EXP on line 427, let's add this same NaN to Null logic there.

**Comment by nbagnard** [comment]
> `POW()` is also used in EXP on line 427, let's add this same NaN to Null logic there.
Good catch! Thanks a lot, I missed this one.
It's fixed now.

**Review by bucaojit — APPROVED** [review]
LGTM

**Comment by nbagnard** [comment]
evergreen merge

**Pull request merged**
